namespace CoreEngine.Application.Features.SafetyIncidents.DTOs;

public record SafetyIncidentDto(
    Guid Id,
    Guid MineSiteId,
    string MineSiteName,
    Guid? MineAreaId,
    string? MineAreaName,
    string IncidentNumber,
    string Title,
    string IncidentType,
    string Severity,
    DateTime IncidentDateTime,
    string Location,
    string Description,
    string? ImmediateActions,
    string ReportedBy,
    DateTime ReportedAt,
    string? InjuredPersonName,
    string? InjuredPersonRole,
    string? InjuryType,
    string? BodyPartAffected,
    int? LostTimeDays,
    bool IsReportable,
    string? RegulatoryReference,
    string? WitnessNames,
    string? RootCause,
    string? ContributingFactors,
    string? CorrectiveActions,
    DateTime? CorrectiveActionDueDate,
    DateTime? CorrectiveActionCompletedDate,
    string Status,
    DateTime CreatedAt,
    int InvestigationCount
);
